### ISSUE TITLE
Primeras recomendaciones

### ISSUE THREAD

**Issue by profesorfaco** [Trabajo-final-Modulo-digital/Areas-Silvestres#1]
Podrían acortar el nombre de su repositorio. El nombre podría referirse al tema de su *fanzine*. Este nombre podría ser tan corto como "perros". Y en el nombre de organización, les recomendaría un nombre menos formal, también corto. 

De esa manera podrán recordar la dirección en donde se publicará. Si no hay cambios, cuando vayan a [Configurar una fuente de publicación para tu sitio Páginas de GitHub](https://docs.github.com/es/free-pro-team@latest/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source) les quedará algo como: 

https://trabajo-final-modulo-digital.github.io/Encargo-Final-Modulo-Digital

En donde sí podrían ser un poco más "formales" es en el README.md, donde conviene evitar referirse al trabajo como: *…esta weaita*…

Buena suerte 👍

**Comment by piasekul** [comment]
Estamos en pleno proceso de desarrollo asique tomaremos todas las sugerencias. Gracias! :-)

**Comment by m4rtina-gonzalez** [comment]
Hola profe!!! tenemos una duda! podemos usar colores extra a los 3 usados en el proyecto gráfico ?

**Comment by profesorfaco** [comment]
¿Extra? Así como agregar dentro del `root{…}` un par de propiedades más, tipo:  
```
--tercercolor: …;
--cuartocolor:…;
```
Si, podrían. Pero les recomiendo ayudarse con esta herramienta de colores de Material Design: https://material.io/resources/color/#!/?view.left=0&view.right=1

Ingresen un "Hex Color" que ya estén usando, y luego revisen qué aparece en P–Light y P–Dark. O sea, recomendaría usar versiones más claras u oscuras del primer y/o segundo color, antes de ir a buscar un color distinto de los anteriores… si tienen muchos colores puros distintos, el resultado podría ser demasiado "colorinche".
